module: src.client.agents.HTTPAgent
parameters:
    url: http://${HOST_IP:-localhost}:11434/api/chat
    headers:
        Content-Type: application/json
    body:
        model: deepseek-coder:6.7b
        stream: false
        temperature: 0
    prompter:
        name: role_content_dict
        args:
            agent_role: assistant
    return_format: "{response[message][content]}"
